### ISSUE TITLE
Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by plaurent-django** [aqeelanwar/DRLwithTL#4]
Hi there,

Ty sir for your impressive work.

Despite my efforts, i can't make it work properly on windows 10. (GPU is 1080, python 3.7)
Please find below my requirements.txt as i can't get tensorflow-gpu 1.4 anymore. ( min version seems to be 1.15.2)

Can you please point me on the right direction ?

Kind regards,

pierre

```
absl-py==0.8.1
airsim==1.2.4
astor==0.8.0
certifi==2018.8.24
cycler==0.10.0
dotmap==1.3.8
gast==0.2.2
google-pasta==0.1.7
grpcio==1.24.1
h5py==2.10.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==3.0.3
msgpack-python==0.5.6
msgpack-rpc-python==0.4.1
numpy==1.17.2
opencv-python==4.1.1.26
opt-einsum==3.1.0
Pillow==6.2.0
protobuf==3.10.0
psutil==5.6.3
pygame==1.9.6
pyparsing==2.4.2
python-dateutil==2.8.0
six==1.12.0
tensorboard==1.15.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.2
termcolor==1.1.0
tornado==4.5.3
Werkzeug==0.16.0
wincertstore==0.2
wrapt==1.11.2

```

Successfully loaded environment: Indoor_Long
------------------------------ Drone ------------------------------
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

------------------------------ DQN ------------------------------
WARNING:tensorflow:From C:\Users\Pierre\Documents\Git\DRLwithTL\network\agent.py:21: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From C:\Users\Pierre\Documents\Git\DRLwithTL\network\agent.py:21: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From C:\Users\Pierre\Documents\Git\DRLwithTL\network\agent.py:30: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\Pierre\Documents\Git\DRLwithTL\network\agent.py:30: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\Users\Pierre\Anaconda3\envs\drl115\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From C:\Users\Pierre\Anaconda3\envs\drl115\lib\site-packages\tensorflow_core\python\ops\image_ops_impl.py:1518: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    agent = DeepAgent(cfg, client, name='DQN')
  File "C:\Users\Pierre\Documents\Git\DRLwithTL\network\agent.py", line 41, in __init__
    self.model = AlexNetDuel(self.X, cfg.num_actions, cfg.train_fc)
  File "C:\Users\Pierre\Documents\Git\DRLwithTL\network\network.py", line 11, in __init__
    weights = np.load(open(weights_path, "rb"), encoding="latin1").item()
  File "C:\Users\Pierre\Anaconda3\envs\drl115\lib\site-packages\numpy\lib\npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\Pierre\Anaconda3\envs\drl115\lib\site-packages\numpy\lib\format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by plaurent-django** [comment]
I've downgraded to numpy 1.16.2, everything is fine. 
[Link](https://stackoverflow.com/questions/55824625/how-to-fix-object-arrays-cannot-be-loaded-when-allow-pickle-false-in-the-sketc/55825320
)
